In [7]:
import numpy as np

# Многомерные массивы
---
<ol>
<li>Создание многомерных массивов Numpy</li>
<li>Доступ к элементам массива</li>
<li>Изменение и копирование массивов</li>
<li>Типы данных Numpy</li>
</ol>

In [8]:
a = [i for i in range(10)]

In [9]:
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [10]:
b = np.array(a)

In [11]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
b = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
b = np.array([i for i in range(10)])

In [15]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
c = (0, 1, 2, 3, 4, 5, 6, 7, 8, 9)

In [17]:
b = np.array(c)

In [18]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
type(b)

numpy.ndarray

In [32]:
b.dtype

dtype('<U3')

ndarray - n-demensial array

Данные одного типа

In [20]:
b = np.array(a, dtype=float)

In [21]:
a = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9.9]

In [24]:
b = np.array(a, dtype = int)

In [25]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
b = np.array(a, dtype = int)

In [27]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
b = np.array(a, dtype = str)

In [29]:
b

array(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9.9'], dtype='<U3')

In [30]:
a = ['123', 1, 2]

In [33]:
b = np.array(a)

In [34]:
b.dtype

dtype('<U11')

In [35]:
b

array(['123', '1', '2'], dtype='<U11')

In [36]:
b[2]

'2'

In [37]:
b[0]

'123'

**Размерность**

In [38]:
b.ndim

1

In [39]:
b.shape

(3,)

**Двумерный массив (2D array)**

In [43]:
b = np.array([[1,2,5],[3,4,6]])

In [44]:
b

array([[1, 2, 5],
       [3, 4, 6]])

In [45]:
b.shape

(2, 3)

2 строки и 3 колонки (столбца)

In [46]:
b.ndim

2

*Количество всех элементов*

In [47]:
b.size

6

In [48]:
b[0][0]

1

In [49]:
b[0,0]

1

In [50]:
b[0:2, 0:3]

array([[1, 2, 5],
       [3, 4, 6]])

In [51]:
b[:2, :2]

array([[1, 2],
       [3, 4]])

In [52]:
b[1:, 2:]

array([[6]])

выше это все N-мерные массивы..!

In [68]:
d = b[1:, :]

In [69]:
d

array([[3, 4, 6]])

In [70]:
b

array([[1, 2, 5],
       [3, 4, 6]])

In [71]:
b[1, 2] = 23414

In [73]:
d

array([[    3,     4, 23414]])

**Пояснение**

Матрицы b и d связаны. d это представление матрицы b. Ссылка на элементы матрицы b. Если меняем в b, то меняем и d.

Применяйте метод copy() чтобы массив d был независимым объектом.


**Data type**

float32, float64, int32, int64

int32 ~ 2_000_0000

# Линейная алгебра
---
<ol>
<li>Сложение и вычитание векторов</li>
<li>Умножение вектора на скаляр</li>
<li>Скалярное произведение векторов</li>
<li>Сложение и вычитание матриц</li>
<li>Умножение матрицы на скаляр</li>
</ol>

**Операции с векторами**

In [74]:
import numpy as np

In [75]:
a = np.array([0,1,2,3,4])

In [76]:
b = np.array([5,6,7,8,9])

In [77]:
a.size

5

In [78]:
b.size

5

In [79]:
a.shape

(5,)

In [80]:
b.shape

(5,)

#### Сложение векторов

In [81]:
c = a + b

In [82]:
c

array([ 5,  7,  9, 11, 13])

Еще один способ:

In [83]:
c = np.add(a, b)

In [84]:
c

array([ 5,  7,  9, 11, 13])

#### Вычитание векторов

In [105]:
a = np.array([5,4,8,4,3])

In [104]:
b = np.array([3,5,7,1,3])

In [88]:
d = a - b
d

array([ 2, -1,  1,  3,  0])

Еще один способ:

In [89]:
d = np.subtract(a,b)

In [90]:
d

array([ 2, -1,  1,  3,  0])

In [92]:
a.shape == b.shape

True

#### Умножение вектора на число

In [93]:
a = np.array([0,1,2,3,4])

In [94]:
c = a * 2

In [95]:
c

array([0, 2, 4, 6, 8])

In [97]:
c = -10 * a

In [98]:
c

array([  0, -10, -20, -30, -40])

Противоположное направление :)

Еще один способ:

In [100]:
np.dot(10, a)

array([ 0, 10, 20, 30, 40])

In [101]:
a.dot(10)

array([ 0, 10, 20, 30, 40])

In [102]:
np.multiply(-10, a)

array([  0, -10, -20, -30, -40])

#### Скалярное произведение

sp = x1 * y1 + x2 * y2 + x3 * y3

@ - оператор add

In [106]:
a @ b

104

In [107]:
sp = np.dot(a,b)

In [108]:
sp

104

#### Операции с матрицами

In [109]:
A = np.array([[0,1],
              [2,3],
              [4,5]])

In [110]:
B = np.array([[6,7],
              [8,9],
              [10,11]])

In [111]:
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [113]:
B

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [114]:
A.shape

(3, 2)

In [115]:
A.ndim

2

In [116]:
A.size

6

In [117]:
B.shape

(3, 2)

In [118]:
B.ndim

2

In [119]:
B.size

6

#### Сложение матриц

In [127]:
D = A + B

In [128]:
D

array([[ 6,  8],
       [10, 12],
       [14, 16]])

In [129]:
D = np.add(A,B)

In [130]:
D

array([[ 6,  8],
       [10, 12],
       [14, 16]])

#### Вычитание матриц

In [135]:
E = A - B
E

array([[-6, -6],
       [-6, -6],
       [-6, -6]])

In [137]:
E = np.subtract(A,B)

In [138]:
E

array([[-6, -6],
       [-6, -6],
       [-6, -6]])

#### Умножение матрицы на скаляр

In [139]:
X = np.array([[1,2],
             [3,4]])

In [140]:
X

array([[1, 2],
       [3, 4]])

In [142]:
Y = X * 2
Y

array([[2, 4],
       [6, 8]])

In [143]:
X.dot(2)

array([[2, 4],
       [6, 8]])

In [144]:
np.dot(X,2)

array([[2, 4],
       [6, 8]])

---

#### Умножение и возведение в степень матриц

In [145]:
import numpy as np

In [146]:
X1 = np.array([[1,2],
               [3,4],
               [5,6]])

In [148]:
X2 = np.array([[7,8,9,10],[11,12,13,14]])

In [149]:
X1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [150]:
X2

array([[ 7,  8,  9, 10],
       [11, 12, 13, 14]])

In [151]:
X1.shape

(3, 2)

In [152]:
X2.shape

(2, 4)

In [154]:
X1.shape[1] == X2.shape[0]

True

In [155]:
Z = np.dot(X1, X2)
Z

array([[ 29,  32,  35,  38],
       [ 65,  72,  79,  86],
       [101, 112, 123, 134]])

In [156]:
Z.shape

(3, 4)

In [157]:
Z.size

12

### Модуль numpy.linalg: возведение матрицы в квадрат

In [158]:
A = np.array([[1,2,3],
               [3,4,5],
               [5,6,7]])

In [159]:
SQ = A * A

In [160]:
SQ

array([[ 1,  4,  9],
       [ 9, 16, 25],
       [25, 36, 49]])

In [163]:
A_square = np.dot(A,A)
A_square

array([[22, 28, 34],
       [40, 52, 64],
       [58, 76, 94]])

In [165]:
A_square = np.linalg.matrix_power(A, 3)
A_square

array([[ 276,  360,  444],
       [ 516,  672,  828],
       [ 756,  984, 1212]])

#### Единичная матрица

Всегда квадратная

In [167]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Транспонирование матриц

In [168]:
A = np.array([[11,13],
              [16,9],
              [8,15]])

In [169]:
At = A.transpose()
At

array([[11, 16,  8],
       [13,  9, 15]])

In [170]:
At = A.T
At

array([[11, 16,  8],
       [13,  9, 15]])

#### Определитель(детерминал) и ранг матрицы

In [171]:
A = np.array([[0,1,2],
              [3,4,5],
              [6,7,8]])

Детерминал:

In [172]:
np.linalg.det(A)

0.0

Ранг:

In [174]:
np.linalg.matrix_rank(A)

2

#### Обратная матрица

Такая матрица, которая при умножении на данную матрицу дает Единичную матрицу :)
Для вычисления обратной матрицы видимо нельзя чтобы были 0 

In [178]:
A = np.array([[2,1,2],
              [3,4,5],
              [6,7,8]])

In [180]:
A_inv = np.linalg.inv(A)

In [181]:
A_inv

array([[ 0.5       , -1.        ,  0.5       ],
       [-1.        , -0.66666667,  0.66666667],
       [ 0.5       ,  1.33333333, -0.83333333]])

In [184]:
np.dot(A, A_inv) 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Генерирование массивов с заданными свойствами
---
<ol>
<li>Автоматическое создание массивов</li>
<li>Генерация случайных чисел</li>
<li>Изменение формы массивов</li>
<li>Соединение формы массивов</li>
</ol>

In [1]:
import numpy as np

#### Автоматическое создание массивов

In [187]:
a = np.zeros((3,4))

In [188]:
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [189]:
a = np.ones((5,3))

In [190]:
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [192]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [193]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [194]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

In [196]:
np.arange(11,1,-2)

array([11,  9,  7,  5,  3])

In [198]:
np.arange(11, 1, -0.1)

array([11. , 10.9, 10.8, 10.7, 10.6, 10.5, 10.4, 10.3, 10.2, 10.1, 10. ,
        9.9,  9.8,  9.7,  9.6,  9.5,  9.4,  9.3,  9.2,  9.1,  9. ,  8.9,
        8.8,  8.7,  8.6,  8.5,  8.4,  8.3,  8.2,  8.1,  8. ,  7.9,  7.8,
        7.7,  7.6,  7.5,  7.4,  7.3,  7.2,  7.1,  7. ,  6.9,  6.8,  6.7,
        6.6,  6.5,  6.4,  6.3,  6.2,  6.1,  6. ,  5.9,  5.8,  5.7,  5.6,
        5.5,  5.4,  5.3,  5.2,  5.1,  5. ,  4.9,  4.8,  4.7,  4.6,  4.5,
        4.4,  4.3,  4.2,  4.1,  4. ,  3.9,  3.8,  3.7,  3.6,  3.5,  3.4,
        3.3,  3.2,  3.1,  3. ,  2.9,  2.8,  2.7,  2.6,  2.5,  2.4,  2.3,
        2.2,  2.1,  2. ,  1.9,  1.8,  1.7,  1.6,  1.5,  1.4,  1.3,  1.2,
        1.1])

**numpy.linspace** - то самое, но нужно учитывать, что правая граница будет включена и вместо шага указывается количество элементов

In [200]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

**numpy.logspace** - границы также включены, но это не сами числа, а степени числа 10

In [202]:
np.logspace(0, 10, 5)

array([1.00000000e+00, 3.16227766e+02, 1.00000000e+05, 3.16227766e+07,
       1.00000000e+10])

In [203]:
np.logspace(0, 3, 4)

array([   1.,   10.,  100., 1000.])

#### Генерация случайных чисел 38:55

**numpy.random.sample** - случайные числа с равномерным распределением в промежутке \[0.0, 1.0)  

In [3]:
np.random.sample()

0.6089291558183658

Одномерный массив из 3 чисел:

In [4]:
np.random.sample(3)

array([0.95105325, 0.65957291, 0.0727264 ])

In [5]:
np.random.sample((2,3))

array([[0.14584271, 0.72428373, 0.36066246],
       [0.76678087, 0.79133167, 0.28661922]])

Случайное изображение с высотой 48, шириной 48 и значением яркости трех цветов для каждого пикселя

In [6]:
np.random.sample((48,48,3))

array([[[0.84395054, 0.16535116, 0.26502411],
        [0.86709979, 0.78303492, 0.05879727],
        [0.71264846, 0.64758446, 0.87563633],
        ...,
        [0.85943634, 0.94929705, 0.83907725],
        [0.45274712, 0.62674589, 0.28299887],
        [0.25103657, 0.41761131, 0.32123832]],

       [[0.64316832, 0.44296915, 0.83251579],
        [0.43724534, 0.54115561, 0.89509511],
        [0.39263328, 0.87109435, 0.35396508],
        ...,
        [0.08252847, 0.96063175, 0.04142474],
        [0.24547339, 0.31942509, 0.0670636 ],
        [0.1114414 , 0.99949495, 0.88319358]],

       [[0.40272132, 0.52442928, 0.52475741],
        [0.33605392, 0.34725752, 0.89692066],
        [0.01462522, 0.18528804, 0.72023983],
        ...,
        [0.12669992, 0.57952202, 0.68916289],
        [0.39968405, 0.43887014, 0.33119212],
        [0.97709314, 0.90304887, 0.59171996]],

       ...,

       [[0.81934099, 0.43622321, 0.4805353 ],
        [0.25807347, 0.78612286, 0.4396968 ],
        [0.20674663, 0

**numpy.random.randn** - случайные числа с нормальным распределением 

(mean = 0, std = 1)

In [15]:
a = np.random.randn(1000)

In [16]:
a.mean()

-0.011216817711719259

In [17]:
a.std()

1.044633769145682

In [18]:
np.random.randn(3,4)

array([[-0.39947801,  0.60387684,  2.76666949,  1.93610023],
       [-0.40604413,  0.58903774,  0.94879819, -1.11274145],
       [ 0.17394171,  0.84444605, -0.56378393,  0.00985828]])

In [21]:
np.random.randn(3,4,2)

array([[[-0.45893187, -0.05210194],
        [ 0.01650822, -0.28424283],
        [ 0.42440718,  0.89500811],
        [-0.47388396,  0.46990398]],

       [[-0.94845112,  0.40727242],
        [ 0.31280222,  0.4633469 ],
        [-0.56158164,  0.33535937],
        [-0.72670138, -0.5759896 ]],

       [[-0.18305423,  0.24814334],
        [ 0.47728308,  1.40195536],
        [-0.82893343, -0.50465304],
        [ 0.22721893, -1.05025628]]])

**numpy.random.randint** - массив из целых чисел

\[0, 100) - промежуток например. Третьим параметром указывается количество, какой массив.
Могут быть повторки...

In [24]:
np.random.randint(90, 100, 10)

array([90, 90, 93, 99, 98, 97, 90, 91, 95, 93])

In [25]:
np.random.randint(0, 100, (3,3))

array([[29, 85, 14],
       [68, 28, 61],
       [64, 31, 40]])

**numppy.random.choice** - случайный выбор элементов из массива

In [26]:
b = np.array((1,4,8,5,3,2,9))

In [37]:
np.random.choice(b)

1

In [48]:
c = np.random.randint(0, 100, 50)

In [50]:
np.random.choice(c,(2,3))

array([[66, 10, 86],
       [56, 52, 16]])

В модуле numpy.random мы получаем не случайные, а псевдослучайные числа. ГСЧ получает объект и генерирует одно и то же. Вот как это работает:

**numpy.random.seed** - инициализация генератора случайных чисел.

Может использоваться для последующей воспроизводимости (будут генерироваться одни и те же числа, если установить одинаковый seed)

In [57]:
np.random.seed(10)

In [58]:
np.random.randint(0, 10, 3)

array([9, 4, 0])

In [59]:
np.random.seed(10)
np.random.randint(0, 10, 3)

array([9, 4, 0])

#### Изменение формы массивов

In [77]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [78]:
a.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [79]:
# Можно указать требуемое число строк, а вместо столбцов поставить -1. Тогда само определится число столбцов :)
a.reshape(2, -1)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [80]:
# как видим массив не изменил свою структуру
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [81]:
# inplace
a.resize(3,4)

In [83]:
# массив изменил форму 
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [84]:
a = a.flatten()

In [86]:
# сделали из многомерного массива одномерный массив. 
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

#### Соединение формы массивов

Для наглядности возьмем два массива - с нулями и единицами:

In [91]:
a = np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [92]:
b = np.ones((2,3))
b

array([[1., 1., 1.],
       [1., 1., 1.]])

In [96]:
np.add(a,b)

array([[1., 1., 1.],
       [1., 1., 1.]])

Соединение строк (горизонтально, вертикально)

In [105]:
h = np.hstack((a,b))
h

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

In [106]:
v = np.vstack((a,b))
v

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [107]:
a.shape, b.shape, h.shape, v.shape

((2, 3), (2, 3), (2, 6), (4, 3))

**Или**

In [108]:
# по вертикали (добавить строки) axis = 0
np.concatenate((a,b), axis = 0) 

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [111]:
# по горизонтали (добавить столбцы) axis = 1
np.concatenate((a,b), axis = 1)

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

Соединение в глубину (В третьем измерении)

In [118]:
d = np.dstack([a,b])

In [119]:
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [120]:
b

array([[1., 1., 1.],
       [1., 1., 1.]])

In [121]:
d

array([[[0., 1.],
        [0., 1.],
        [0., 1.]],

       [[0., 1.],
        [0., 1.],
        [0., 1.]]])

# Функции для работы с данными 
---
<ol>
<li>Выбор данных из массива</li>
<li>Сортировка</li>
<li>Случайное перемешивание</li>
<li>Математические действия</li>
<li>Broadcasting</li>
<li>Статические функции</li>
<li>Запись и чтение массивов из файла</li>
</ol>

In [122]:
import numpy as np

#### Выбор данных

In [125]:
a = np.random.randint(0, 20, 10)
a

array([19, 13,  5, 13, 19, 13, 12,  1,  4, 18])

***булевы маски***

In [127]:
# Булева маска
a[a > 10]

array([19, 13, 13, 19, 13, 12, 18])

In [129]:
a[(a > 10) & (a % 2 == 0)]

array([12, 18])

In [130]:
a[(a > 10) | (a % 3 == 0)]

array([19, 13, 13, 19, 13, 12, 18])

Вариант без булевых масок

**numpy.where** - возвращает индексы тек элементов, которые соответствуют условию. Таким образом на выходе массив индексов

In [131]:
a

array([19, 13,  5, 13, 19, 13, 12,  1,  4, 18])

In [132]:
np.where(a > 10)

(array([0, 1, 3, 4, 5, 6, 9], dtype=int64),)

In [133]:
a[np.where(a > 10)]

array([19, 13, 13, 19, 13, 12, 18])

Очень крутая штука с where:

In [134]:
a = [1, 4, 7]
b = [9,2,5]

In [136]:
# Если в условии True, то берем из массива а, если False - то из b
np.where([True, False, True], a, b)

array([1, 2, 7])

In [137]:
np.where([1, 0, 1], a, b)

array([1, 2, 7])

#### Сортировка

In [140]:
a = np.array([[1,3,9,9],
              [5,0,1,5],
              [2,7,3,5]])
a

array([[1, 3, 9, 9],
       [5, 0, 1, 5],
       [2, 7, 3, 5]])

Хотим отсортировать данный массив по нулевому столбцу (1,5,2)

In [143]:
a[[0,2,1],:]

array([[1, 3, 9, 9],
       [2, 7, 3, 5],
       [5, 0, 1, 5]])

In [144]:
type(a)

numpy.ndarray

**numpy.ndarray.argsort** - сортировка по осям. возвращает массив с индексами вместо значений

In [145]:
a.argsort(axis = 0)

array([[0, 1, 1, 1],
       [2, 0, 2, 2],
       [1, 2, 0, 0]], dtype=int64)

In [147]:
a[:, 0]

array([1, 5, 2])

In [157]:
a[:, 0].argsort()

array([0, 2, 1], dtype=int64)

In [151]:
a[a[:, 0].argsort(),:]

array([[1, 3, 9, 9],
       [2, 7, 3, 5],
       [5, 0, 1, 5]])

Пояснение: мы вначале отсортировали столбец 0, и взяли индексы. Потом мы эти индексы сунули в строковые индексы и взяли фулл индексы по столбцу

#### Случайное перемешивание

Операция обратная сортировке. Иногда в машинном обучении выборки нужно перемешивать :)

Одномерные массивы

In [164]:
a = np.random.randint(0,1000,10)
a

array([554, 749, 313, 747, 865, 818, 557, 936, 985, 713])

In [165]:
# inplace - меняет массив (как в resize)
np.random.shuffle(a)

In [166]:
a

array([749, 557, 936, 865, 985, 713, 747, 313, 554, 818])

In [167]:
a = np.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [169]:
# inplace
np.random.shuffle(a)

In [170]:
a

array([[ 9, 10, 11],
       [ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8]])

Пояснение: **numpy.random.shuffle** - полностью перемешивают одномерные массивы. В остальных случаях перемешиваются только строки (у строк меняются индексы, внутри все также)

#### Математические действия

Применение математических действий ко всему массиву

In [173]:
a = np.arange(1,7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [174]:
# Логарифм по основанию е
np.log(a)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947]])

In [175]:
# exp
np.exp(a)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [176]:
a.sum()

21

In [177]:
a.sum(axis=0)

array([5, 7, 9])

In [178]:
a.sum(axis = 1)

array([ 6, 15])

In [179]:
10 + a

array([[11, 12, 13],
       [14, 15, 16]])

Поэлементоне умножение (не матричное):

In [181]:
b = np.arange(12).reshape(3,-1)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [184]:
a = np.arange(12,24).reshape(3,-1)
a

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [185]:
a * b

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

#### Broadcasting (на примере сложения)

In [186]:
a = np.array([[2,5],
              [3,4],
              [6,1]])

1 случай - совпадает только число столбцов

In [187]:
b = np.array([1,2])

In [188]:
a.shape, b.shape

((3, 2), (2,))

In [189]:
a + b

array([[3, 7],
       [4, 6],
       [7, 3]])

Прибавили строку b ко всем строкам a

2 случай - совпадает только число строк

In [190]:
a

array([[2, 5],
       [3, 4],
       [6, 1]])

In [193]:
c = np.array([[1],
              [2],
              [3]])
c

array([[1],
       [2],
       [3]])

In [194]:
a + c

array([[3, 6],
       [5, 6],
       [9, 4]])

Прибавили столбец с ко всем столбцам a

#### Статические функции

Основные:

In [196]:
a = np.random.randint(0, 12, (3,4))
a

array([[ 5,  9,  0, 10],
       [ 1,  0,  1,  9],
       [ 0,  9, 10,  2]])

In [197]:
# Минимум
a.min()

0

In [198]:
a.min(axis=0)

array([0, 0, 0, 2])

In [200]:
# Максимум
a.max()

10

In [201]:
a.max(axis = 1)

array([10,  9, 10])

In [202]:
# Среднее значение
a.mean()

4.666666666666667

In [205]:
# Среднеквадратичное отклонение
a.std()

4.20977698010503

In [206]:
a.mean(axis = 0)

array([2.        , 6.        , 3.66666667, 7.        ])

In [207]:
a.std(axis = 0)

array([2.1602469 , 4.24264069, 4.49691252, 3.55902608])

#### Запись и чтение массивов из файла

Запись массива *а* в файл 'a.npy'

In [208]:
np.save('a.npy', a)

Чтение массива из файла

In [210]:
np.load('a.npy')

array([[ 5,  9,  0, 10],
       [ 1,  0,  1,  9],
       [ 0,  9, 10,  2]])